O2M/Models/Parceiro/AlterarSenhaVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace O2M.Models.Parceiro
{
    public class AlterarSenhaVM
    {
        [DisplayName("Senha Antiga")]
        public string SenhaAntiga { get; set; }

        [DisplayName("Senha Nova")]
        public string SenhaNova { get; set; }

        [DisplayName("Repetir Senha Nova")]
        public string SenhaNova2 { get; set; }
    }
}

O2M/Controllers/ParceiroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DAO.Repositories;
using Model.Entities;
using O2M.Models.Parceiro;

namespace O2M.Controllers
{
    public class ParceiroController : BaseController
    {
        // GET: Parceiro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastro(Parceiro p)
        {
            var bancos = new UOW().BancoRep.Get(pagesize:999, orderBy: q => q.OrderBy(a => a.CodBanco)).Select(b => new SelectListItem() { Value = b.CodBanco.ToString(), Text = b.Nome }).ToList();

            ViewBag.bancos = bancos;
            if (ModelState.IsValid)
            {
                var uow = new UOW();
                p.Token = Util.Crypto.ConvertSHA1(DateTime.Now.ToString());
                uow.ParceiroRep.Insert(p);
                uow.Save();
                return RedirectToAction("Login");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Login(string login, string senha)
        {
            if (Request.HttpMethod == "GET")
            {
                return View();
            }
            var uow = new UOW();
            senha = Util.Crypto.ConvertSHA1(senha);
            var parceiro = uow.ParceiroRep.GetFirst(p => p.Email == login && p.Senha == senha, orderBy: o => o.OrderBy( u => u.CodParceiro));
            if (parceiro != null)
            {
                FormsAuthentication.SetAuthCookie(parceiro.CodParceiro.ToString(), false);
                if (parceiro.IsAdmin)
                {
                    return RedirectToAction("ListarLeads", "Admin");
                }
                return RedirectToAction("Index","Home");
            }
            return View();
        }

        public ActionResult Logoff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Editar(Parceiro p = null)
        {
            var codParceiro = Convert.ToInt32(User.Identity.Name);
            var bancos = new UOW().BancoRep.Get(pagesize: 999, orderBy: q => q.OrderBy(a => a.CodBanco)).Select(b => new SelectListItem() { Value = b.CodBanco.ToString(), Text = b.Nome }).ToList();
            ViewBag.bancos = bancos;
            var parceiro = new UOW().ParceiroRep.GetFirst(pa => pa.CodParceiro == codParceiro);
            if (Request.HttpMethod == "POST")
            {
                if (ModelState.IsValid)
                {
                    p.Nome = parceiro.Nome;
                    p.CodParceiro = parceiro.CodParceiro;
                    p.Documento = parceiro.Documento;
                    p.Email = parceiro.Email;
                    var uow = new UOW();
                    if (String.IsNullOrEmpty(p.Senha))
                    {
                        p.setSenhaSemMod(parceiro.Senha);
                    }
                    uow.ParceiroRep.Update(p);
                    return View();
                }
            }
            
            return View(parceiro);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult AlterarSenha(AlterarSenhaVM model)
        {
            try
            {
                var codParceiro = Convert.ToInt32(User.Identity.Name);
                if (Request.HttpMethod == "POST")
                {
                    if (ModelState.IsValid)
                    {
                        if (model.SenhaNova != model.SenhaNova2)
                        {
                            ModelState.AddModelError("SenhaNova", "Senhas não conferem");
                            return View();
                        }
                        else
                        {
                            var uow = new UOW();
                            var senha = Util.Crypto.ConvertSHA1(model.SenhaNova);
                            if (uow.ParceiroRep.GetFirst(p => p.CodParceiro == codParceiro && p.Senha == senha) == null)
                            {
                                ModelState.AddModelError("Senha", "Senha atual incorreta.");
                            }
                            else
                            {
                                var parceiro = uow.ParceiroRep.GetFirst(p => p.CodParceiro == codParceiro);
                                parceiro.Senha = model.SenhaNova;
                                uow.ParceiroRep.Update(parceiro);
                                uow.Save();
                                return RedirectToAction("Index", "Home");
                            }
                        }
                    }
                }
                return View();

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
}

O2M/Views/Parceiro/Cadastro.cshtml
@model Model.Entities.Parceiro

@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Parceiro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Documento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Documento, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Senha,  new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Senha, "",  new { @class = "text-danger" })
            </div>
        </div>
        

        <hr />
        <H5>Dados Bancários</H5>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Banco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodBanco", (List<SelectListItem>)ViewBag.bancos, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Banco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Agencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Agencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agencia, "", new { @class = "text-danger" })
            </div>
        </div>
        
        

        <div class="form-group">
            @Html.LabelFor(model => model.Conta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Conta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Conta, "", new { @class = "text-danger" })
            </div>
        </div>

        


        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

O2M/Views/Parceiro/Editar.cshtml
@model Model.Entities.Parceiro

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Parceiro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr/>
        
        <h5>Dados Bancários</h5>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Banco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodBanco", (List<SelectListItem>)ViewBag.bancos, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Banco, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Conta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Conta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Conta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Agencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agencia, "", new { @class = "text-danger" })
            </div>
        </div>

        

        

       

        

        

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

O2M/Views/Parceiro/Login.cshtml
@{
    ViewBag.Title = "Login";
}





<h2>Login</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-3 col-sm-3"></div>
        <div class="col-xs-12 col-sm-6 col-md-5 col-lg-4">
            @using (Html.BeginForm())
            {


                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="col-lg-12">
                            <div><img src="~/Content/logo.png" /></div>
                            <div class="row">
                                <h2 class="text-center login-title">@ViewBag.Texto1</h2>
                                <h4 class="text-center login-title">Faça seu Login</h4>
                            </div>
                            <hr/>
                            <form action="">
                                <div class="row">
                                    <div class="col-lg-12">

                                        @Html.TextBox("login", "", new {@class = "form-control", placeholder= "E-mail"})
                                        <input type="password" class="form-control" name="Senha" placeholder="Senha"/>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <input type="submit" class="btn btn-primary" value="Entrar"/>

                                    </div>
                                </div>
                                <div class="row" style="margin-top: 8px;">
                                    
                                    <div class="col-sm-12">
                                        <small>Ou então <a href="@Url.Action("Cadastro", "Parceiro")">cadastre-se</a></small> <br/>
                                        
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>